CREATE TABLE region (
    region_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    si VARCHAR(20) NOT NULL,
    gun VARCHAR(20) NOT NULL,
    gu VARCHAR(30) NOT NULL
);

CREATE TABLE roles (
    roles_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL,
    accessible_entity VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_roles_name UNIQUE (name),
    CONSTRAINT ck_roles_name CHECK (name IN ('ADMIN', 'USER', 'DEV'))
);

CREATE TABLE agreement (
    agreement_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    content VARCHAR(8000) NOT NULL,
    version VARCHAR(8) NOT NULL,
    is_required BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE member (
    member_id VARCHAR(36) PRIMARY KEY,
    preferred_region INTEGER,
    email VARCHAR(100),
    password VARCHAR(100),
    provider VARCHAR(20) NOT NULL,
    provider_user_id VARCHAR(255),
    nickname VARCHAR(50) NOT NULL,
    profile_image VARCHAR(2048) NOT NULL DEFAULT '/images/default-profile.png',
    preferred_theme VARCHAR(20),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_member_email_provider UNIQUE (email, provider),
    CONSTRAINT fk_member_preferred_region
        FOREIGN KEY (preferred_region) REFERENCES region (region_id),
    CONSTRAINT ck_member_provider CHECK (provider IN ('LOCAL', 'GOOGLE', 'KAKAO')),
    CONSTRAINT ck_member_local_password CHECK (
        (provider = 'LOCAL' AND password IS NOT NULL)
        OR (provider <> 'LOCAL' AND password IS NULL)
    )
);

CREATE TABLE member_roles (
    member_role_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id VARCHAR(36) NOT NULL,
    roles_id INTEGER NOT NULL,
    CONSTRAINT uk_member_roles UNIQUE (member_id, roles_id),
    CONSTRAINT fk_member_roles_member
        FOREIGN KEY (member_id) REFERENCES member (member_id),
    CONSTRAINT fk_member_roles_roles
        FOREIGN KEY (roles_id) REFERENCES roles (roles_id)
);

CREATE TABLE member_agreement (
    member_agreement_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agreement_id INTEGER NOT NULL,
    member_id VARCHAR(36) NOT NULL,
    is_agreement BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_member_agreement UNIQUE (member_id, agreement_id),
    CONSTRAINT fk_member_agreement_agreement
        FOREIGN KEY (agreement_id) REFERENCES agreement (agreement_id),
    CONSTRAINT fk_member_agreement_member
        FOREIGN KEY (member_id) REFERENCES member (member_id)
);

COMMENT ON TABLE region IS '지역';
COMMENT ON COLUMN region.region_id IS '지역 식별자';
COMMENT ON COLUMN region.si IS '시';
COMMENT ON COLUMN region.gun IS '군';
COMMENT ON COLUMN region.gu IS '구';

COMMENT ON TABLE roles IS '권한';
COMMENT ON COLUMN roles.roles_id IS '권한 식별자';
COMMENT ON COLUMN roles.name IS '권한 이름';
COMMENT ON COLUMN roles.accessible_entity IS '접근 가능 엔티티';
COMMENT ON COLUMN roles.created_at IS '생성 날짜';
COMMENT ON COLUMN roles.deleted_at IS '삭제 날짜';

COMMENT ON TABLE agreement IS '약관';
COMMENT ON COLUMN agreement.agreement_id IS '약관 식별자';
COMMENT ON COLUMN agreement.title IS '약관 제목';
COMMENT ON COLUMN agreement.content IS '약관 내용';
COMMENT ON COLUMN agreement.version IS '약관 버전';
COMMENT ON COLUMN agreement.is_required IS '필수 여부';
COMMENT ON COLUMN agreement.created_at IS '생성 날짜';
COMMENT ON COLUMN agreement.updated_at IS '수정 날짜';
COMMENT ON COLUMN agreement.is_deleted IS '삭제 여부';

COMMENT ON TABLE member IS '유저';
COMMENT ON COLUMN member.member_id IS '유저 식별자';
COMMENT ON COLUMN member.preferred_region IS '선호 지역';
COMMENT ON COLUMN member.email IS '이메일';
COMMENT ON COLUMN member.password IS '비밀번호';
COMMENT ON COLUMN member.provider IS '소셜 로그인 구분자';
COMMENT ON COLUMN member.provider_user_id IS '소셜 로그인 제공자 사용자 식별자';
COMMENT ON COLUMN member.nickname IS '닉네임';
COMMENT ON COLUMN member.profile_image IS '프로필 이미지';
COMMENT ON COLUMN member.preferred_theme IS '선호 테마';
COMMENT ON COLUMN member.is_active IS '활성화 여부';
COMMENT ON COLUMN member.created_at IS '생성 날짜';
COMMENT ON COLUMN member.updated_at IS '수정 날짜';

COMMENT ON TABLE member_roles IS '유저_권한';
COMMENT ON COLUMN member_roles.member_role_id IS '유저_권한 식별자';
COMMENT ON COLUMN member_roles.member_id IS '유저 식별자';
COMMENT ON COLUMN member_roles.roles_id IS '권한 식별자';

COMMENT ON TABLE member_agreement IS '유저_약관';
COMMENT ON COLUMN member_agreement.member_agreement_id IS '유저_약관 식별자';
COMMENT ON COLUMN member_agreement.agreement_id IS '약관 식별자';
COMMENT ON COLUMN member_agreement.member_id IS '유저 식별자';
COMMENT ON COLUMN member_agreement.is_agreement IS '동의 여부';
COMMENT ON COLUMN member_agreement.created_at IS '생성 날짜';
COMMENT ON COLUMN member_agreement.updated_at IS '수정 날짜';
COMMENT ON COLUMN member_agreement.is_deleted IS '삭제 여부';
