CREATE TABLE password_blocklist (
                                    password_blocklist_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    word VARCHAR(100) NOT NULL,
                                    match_type VARCHAR(20) NOT NULL,
                                    enabled BOOLEAN NOT NULL DEFAULT TRUE,
                                    CONSTRAINT ck_password_blocklist_match_type
                                        CHECK (match_type IN ('CONTAINS', 'EXACT'))
);

CREATE TABLE nickname_blocklist (
                                    nickname_blocklist_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    word VARCHAR(100) NOT NULL,
                                    match_type VARCHAR(20) NOT NULL,
                                    enabled BOOLEAN NOT NULL DEFAULT TRUE,
                                    CONSTRAINT ck_nickname_blocklist_match_type
                                        CHECK (match_type IN ('CONTAINS', 'EXACT'))
);

COMMENT ON TABLE password_blocklist IS '비밀번호 금칙어';
COMMENT ON COLUMN password_blocklist.password_blocklist_id IS '비밀번호 금칙어 식별자';
COMMENT ON COLUMN password_blocklist.word IS '금칙어';
COMMENT ON COLUMN password_blocklist.match_type IS '일치 유형';
COMMENT ON COLUMN password_blocklist.enabled IS '활성화 여부';

COMMENT ON TABLE nickname_blocklist IS '닉네임 금칙어';
COMMENT ON COLUMN nickname_blocklist.nickname_blocklist_id IS '닉네임 금칙어 식별자';
COMMENT ON COLUMN nickname_blocklist.word IS '금칙어';
COMMENT ON COLUMN nickname_blocklist.match_type IS '일치 유형';
COMMENT ON COLUMN nickname_blocklist.enabled IS '활성화 여부';

CREATE INDEX idx_password_blocklist_lookup
    ON password_blocklist (word, match_type, enabled);

CREATE INDEX idx_nickname_blocklist_lookup
    ON nickname_blocklist (word, match_type, enabled);